/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Aux.GameLogic;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author alanvega
 */
public class Game extends javax.swing.JFrame {

    /**
     * Creates new form Game
     */
    private GameLogic log = new GameLogic();
    private boolean Up = false;
    private ImageIcon Im1;
    private ImageIcon Im2;
    private JButton[] gcard = new JButton[2];
    private boolean first = false;
    private int score = 0;
    public Game() {
        initComponents();
        SetCards();
    }
    private void SetCards(){
      int[] numbers = log.getCardNumbers();
      Card1.setDisabledIcon(new ImageIcon(getClass().getResource("../Images/c" + numbers[0] + ".png")));
      Card2.setDisabledIcon(new ImageIcon(getClass().getResource("../Images/c" + numbers[1] + ".png")));
      Card3.setDisabledIcon(new ImageIcon(getClass().getResource("../Images/c" + numbers[2] + ".png")));
      Card4.setDisabledIcon(new ImageIcon(getClass().getResource("../Images/c" + numbers[3] + ".png")));
      Card5.setDisabledIcon(new ImageIcon(getClass().getResource("../Images/c" + numbers[4] + ".png")));
      Card6.setDisabledIcon(new ImageIcon(getClass().getResource("../Images/c" + numbers[5] + ".png")));
      Card7.setDisabledIcon(new ImageIcon(getClass().getResource("../Images/c" + numbers[6] + ".png")));
      Card8.setDisabledIcon(new ImageIcon(getClass().getResource("../Images/c" + numbers[7] + ".png")));
    }
    
    private void CardEnabled(JButton Card){
    
        if(!Up){
        Card.setEnabled(false);
        Im1 = (ImageIcon) Card.getDisabledIcon();
        gcard[0] = Card;
        Up = true;
        first = false;
        }
        else{
        Card.setEnabled(false);
        Im2 = (ImageIcon) Card.getDisabledIcon();
        gcard[1] = Card;
        first = true;
        score += 20;
        Puntaje.setText("Su puntaje actual es: " + score);
        }
        
    }
    
    private void compare(){
        if(Up && first){
        
            if(Im1.getDescription().compareTo(Im2.getDescription()) != 0){
                gcard[0].setEnabled(true);
                gcard[1].setEnabled(true);
                if (score > 10){
                    score -= 10;
                    Puntaje.setText("Su puntaje actual es: " + score);
                }
                
            }else{
            gcard[0].setVisible(false);
            gcard[1].setVisible(false);
            
            }
            Up = false;
        }
        
    }
    
    private void reiniciar(){
        Card1.setEnabled(true);
        Card2.setEnabled(true);
        Card3.setEnabled(true);
        Card4.setEnabled(true);
        Card5.setEnabled(true);
        Card6.setEnabled(true);
        Card7.setEnabled(true);
        Card8.setEnabled(true);
        Card1.setVisible(true);
        Card2.setVisible(true);
        Card3.setVisible(true);
        Card4.setVisible(true);
        Card5.setVisible(true);
        Card6.setVisible(true);
        Card7.setVisible(true);
        Card8.setVisible(true);
        first = false;
        Up = false;
        SetCards();
        score = 0;
        Puntaje.setText("Su puntaje actual es: " + score);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Card1 = new javax.swing.JButton();
        Card2 = new javax.swing.JButton();
        Card3 = new javax.swing.JButton();
        Card4 = new javax.swing.JButton();
        Card5 = new javax.swing.JButton();
        Card6 = new javax.swing.JButton();
        Card7 = new javax.swing.JButton();
        Card8 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Restart = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Puntaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bienvenido al Juego de Memorama");

        Card1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Modelo de Carta sin voltear.png"))); // NOI18N
        Card1.setBorder(null);
        Card1.setBorderPainted(false);
        Card1.setContentAreaFilled(false);
        Card1.setFocusable(false);
        Card1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Card1MouseExited(evt);
            }
        });
        Card1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Card1ActionPerformed(evt);
            }
        });

        Card2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Modelo de Carta sin voltear.png"))); // NOI18N
        Card2.setBorder(null);
        Card2.setBorderPainted(false);
        Card2.setContentAreaFilled(false);
        Card2.setFocusable(false);
        Card2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Card2MouseExited(evt);
            }
        });
        Card2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Card2ActionPerformed(evt);
            }
        });

        Card3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Modelo de Carta sin voltear.png"))); // NOI18N
        Card3.setBorder(null);
        Card3.setBorderPainted(false);
        Card3.setContentAreaFilled(false);
        Card3.setFocusable(false);
        Card3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Card3MouseExited(evt);
            }
        });
        Card3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Card3ActionPerformed(evt);
            }
        });

        Card4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Modelo de Carta sin voltear.png"))); // NOI18N
        Card4.setBorder(null);
        Card4.setBorderPainted(false);
        Card4.setContentAreaFilled(false);
        Card4.setFocusable(false);
        Card4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Card4MouseExited(evt);
            }
        });
        Card4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Card4ActionPerformed(evt);
            }
        });

        Card5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Modelo de Carta sin voltear.png"))); // NOI18N
        Card5.setBorder(null);
        Card5.setBorderPainted(false);
        Card5.setContentAreaFilled(false);
        Card5.setFocusable(false);
        Card5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Card5MouseExited(evt);
            }
        });
        Card5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Card5ActionPerformed(evt);
            }
        });

        Card6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Modelo de Carta sin voltear.png"))); // NOI18N
        Card6.setBorder(null);
        Card6.setBorderPainted(false);
        Card6.setContentAreaFilled(false);
        Card6.setFocusable(false);
        Card6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Card6MouseExited(evt);
            }
        });
        Card6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Card6ActionPerformed(evt);
            }
        });

        Card7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Modelo de Carta sin voltear.png"))); // NOI18N
        Card7.setBorder(null);
        Card7.setBorderPainted(false);
        Card7.setContentAreaFilled(false);
        Card7.setFocusable(false);
        Card7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Card7MouseExited(evt);
            }
        });
        Card7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Card7ActionPerformed(evt);
            }
        });

        Card8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Modelo de Carta sin voltear.png"))); // NOI18N
        Card8.setBorder(null);
        Card8.setBorderPainted(false);
        Card8.setContentAreaFilled(false);
        Card8.setFocusable(false);
        Card8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Card8MouseExited(evt);
            }
        });
        Card8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Card8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Card5)
                        .addGap(18, 18, 18)
                        .addComponent(Card6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Card1)
                        .addGap(18, 18, 18)
                        .addComponent(Card2)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Card3)
                        .addGap(18, 18, 18)
                        .addComponent(Card4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Card7)
                        .addGap(18, 18, 18)
                        .addComponent(Card8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Card1, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                    .addComponent(Card2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Card3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Card4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Card5, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(Card6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Card8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addComponent(Card7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jLabel2.setText("Hecho por Alan V, Iker y Merry");

        Restart.setText("Reinicio");
        Restart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestartActionPerformed(evt);
            }
        });

        Puntaje.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addComponent(Restart))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Puntaje, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addComponent(Restart))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel3)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Puntaje, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(4, 4, 4))))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Card1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Card1ActionPerformed
        // TODO add your handling code here:
        CardEnabled(Card1);
    }//GEN-LAST:event_Card1ActionPerformed

    private void Card2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Card2ActionPerformed
        // TODO add your handling code here:
        CardEnabled(Card2);
    }//GEN-LAST:event_Card2ActionPerformed

    private void Card3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Card3ActionPerformed
        // TODO add your handling code here:
        CardEnabled(Card3);
    }//GEN-LAST:event_Card3ActionPerformed

    private void Card4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Card4ActionPerformed
        // TODO add your handling code here:
        CardEnabled(Card4);
    }//GEN-LAST:event_Card4ActionPerformed

    private void Card5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Card5ActionPerformed
        // TODO add your handling code here:
        CardEnabled(Card5);
    }//GEN-LAST:event_Card5ActionPerformed

    private void Card6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Card6ActionPerformed
        // TODO add your handling code here:
        CardEnabled(Card6);
    }//GEN-LAST:event_Card6ActionPerformed

    private void Card7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Card7ActionPerformed
        // TODO add your handling code here:
        CardEnabled(Card7);
    }//GEN-LAST:event_Card7ActionPerformed

    private void Card8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Card8ActionPerformed
        // TODO add your handling code here:
        CardEnabled(Card8);
    }//GEN-LAST:event_Card8ActionPerformed

    private void Card1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Card1MouseExited
        // TODO add your handling code here:
        compare();
    }//GEN-LAST:event_Card1MouseExited

    private void Card2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Card2MouseExited
        // TODO add your handling code here:
        compare();
    }//GEN-LAST:event_Card2MouseExited

    private void Card3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Card3MouseExited
        // TODO add your handling code here:
        compare();
    }//GEN-LAST:event_Card3MouseExited

    private void Card4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Card4MouseExited
        // TODO add your handling code here:
        compare();
    }//GEN-LAST:event_Card4MouseExited

    private void Card5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Card5MouseExited
        // TODO add your handling code here:
        compare();
    }//GEN-LAST:event_Card5MouseExited

    private void Card6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Card6MouseExited
        // TODO add your handling code here:
        compare();
    }//GEN-LAST:event_Card6MouseExited

    private void Card7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Card7MouseExited
        // TODO add your handling code here:
        compare();
    }//GEN-LAST:event_Card7MouseExited

    private void Card8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Card8MouseExited
        // TODO add your handling code here:
        compare();
    }//GEN-LAST:event_Card8MouseExited

    private void RestartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestartActionPerformed
        // TODO add your handling code here:
        reiniciar();
    }//GEN-LAST:event_RestartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Card1;
    private javax.swing.JButton Card2;
    private javax.swing.JButton Card3;
    private javax.swing.JButton Card4;
    private javax.swing.JButton Card5;
    private javax.swing.JButton Card6;
    private javax.swing.JButton Card7;
    private javax.swing.JButton Card8;
    private javax.swing.JLabel Puntaje;
    private javax.swing.JButton Restart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
