
import java.awt.Color;

//Estimado Colega programador
//Cuando Xtreme y yo escribimos este sistema, solo nosotros y Dios sabíamos como funcionaba
//AHORA SOLO DIOS LO SABE!!!
//Así que si estás tratando de hacerlo funcionar y fracasas (seguramente)
//por favor, incremente el contador a continuación
//Creepe dice que sirve para contar, creo que tiene razón
//Para más información, visite el Diario 1 卐卐卐
//Atte: Zoren
//Total de horas perdidas en favor del estado: 84 ☭☭☭
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ikerf
 */
public class ButtonExcercise_1 extends javax.swing.JFrame {
    int count;
    int score;
    boolean carta1 = false;
    boolean carta2 = false;
    boolean carta3 = false;
    boolean carta4 = false;
    boolean carta5 = false;
    boolean carta6 = false;
    boolean carta7 = false;
    boolean carta8 = false;
    int poscx_1 = 50;
    int poscx_2 = 5;
    int poscx_3 = 10;
    int poscx_4 = 15;
    int poscx_5 = 20;
    int poscx_6 = 25;
    int poscx_7 = 30;
    int poscx_8 = 250;

    int poscy_1 = 50;
    int poscy_2 = 5;
    int poscy_3 = 10;
    int poscy_4 = 15;
    int poscy_5 = 20;
    int poscy_6 = 25;
    int poscy_7 = 30;
    int poscy_8 = 200;
    int i = (int)Math.floor(Math.random()*8+1);
    int j = (int)Math.floor(Math.random()*8+1);
    int k = (int)Math.floor(Math.random()*8+1);
    int l = (int)Math.floor(Math.random()*8+1);
    int m = (int)Math.floor(Math.random()*8+1);
    int n = (int)Math.floor(Math.random()*8+1);
    int o = (int)Math.floor(Math.random()*8+1);
    int p = (int)Math.floor(Math.random()*8+1);
    
    private Randomization rand = new Randomization();
    

    /**
     * Creates new form ButtonExcercise
     */
    public ButtonExcercise_1() {
        
        
        initComponents();
        SetCards();
    }
    private void SetCards(){
      int[] numbers = rand.getCardNumbers();
      Carta1.getClass().getResource("" + numbers[0]);
      Carta2.getClass().getResource("" + numbers[1]);
      Carta3.getClass().getResource("" + numbers[2]);
      Cart4.getClass().getResource("" + numbers[3]);
      Carta5.getClass().getResource("" + numbers[4]);
      Carta6.getClass().getResource("" + numbers[5]);
      Carta7.getClass().getResource("" + numbers[6]);
      Carta8.getClass().getResource("" + numbers[7]);
    }
    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Carta1 = new javax.swing.JToggleButton();
        Carta7 = new javax.swing.JToggleButton();
        Carta5 = new javax.swing.JToggleButton();
        Carta6 = new javax.swing.JToggleButton();
        Carta2 = new javax.swing.JToggleButton();
        Carta8 = new javax.swing.JToggleButton();
        Cart4 = new javax.swing.JToggleButton();
        Carta3 = new javax.swing.JToggleButton();
        SCORE = new javax.swing.JLabel();
        Reinicio = new javax.swing.JButton();
        counts = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Apuchurrale_Starp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Carta1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Carta1MouseClicked(evt);
            }
        });
        Carta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Carta1ActionPerformed(evt);
            }
        });

        Carta7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Carta7MouseClicked(evt);
            }
        });

        Carta5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Carta5MouseClicked(evt);
            }
        });

        Carta6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Carta6MouseClicked(evt);
            }
        });

        Carta2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Carta2MouseClicked(evt);
            }
        });
        Carta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Carta2ActionPerformed(evt);
            }
        });

        Carta8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Carta8MouseClicked(evt);
            }
        });

        Cart4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Cart4MouseClicked(evt);
            }
        });

        Carta3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Carta3MouseClicked(evt);
            }
        });

        SCORE.setText("Score");

        Reinicio.setText("Reiniciar_c");
        Reinicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReinicioMouseClicked(evt);
            }
        });
        Reinicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReinicioActionPerformed(evt);
            }
        });

        counts.setText("count");

        jLabel1.setText("lker, Alan, Merry");

        jLabel2.setText("SCORE:");

        Apuchurrale_Starp.setText("Start");
        Apuchurrale_Starp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Apuchurrale_StarpMouseClicked(evt);
            }
        });
        Apuchurrale_Starp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Apuchurrale_StarpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Reinicio)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Carta1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(Carta5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Carta2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Carta6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Apuchurrale_Starp, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(counts))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Carta7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Carta3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Cart4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SCORE)
                                    .addComponent(jLabel2)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Carta8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Carta3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Carta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Carta2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Cart4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Carta7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Carta6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Carta5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Carta8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SCORE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(counts, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Reinicio)
                            .addComponent(Apuchurrale_Starp))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Carta1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Carta1MouseClicked
        // TODO add your handling code here:
        
        Carta1.setBackground(Color.yellow);
        carta1 = true;
        count++;
        counts.setText(String.valueOf(count));
        if(carta2 == true){
             Carta1.setVisible(false);
             Carta2.setVisible(false);
             
             score++;
             count = 0;
         carta1 = false;
         carta2 = false;
         carta3 = false;
         carta4 = false;
         carta5 = false;
         carta6 = false;
         carta7 = false;
         carta8 = false;
             Carta1.setBackground(Color.gray);
             Carta2.setBackground(Color.gray);
             
        }
         else if(count >= 2){
         Carta1.setBackground(Color.gray);
         Carta2.setBackground(Color.gray);
         Carta3.setBackground(Color.gray);
         Cart4.setBackground(Color.gray);
         Carta5.setBackground(Color.gray);
         Carta6.setBackground(Color.gray);
         Carta7.setBackground(Color.gray);
         Carta8.setBackground(Color.gray);
         

         carta1 = false;
         carta2 = false;
         carta3 = false;
         carta4 = false;
         carta5 = false;
         carta6 = false;
         carta7 = false;
         carta8 = false;
         count = 0;
         
         }
        SCORE.setText(String.valueOf(score));
        
    }//GEN-LAST:event_Carta1MouseClicked

    private void Carta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Carta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Carta1ActionPerformed

    private void Carta2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Carta2MouseClicked
        // TODO add your handling code here:
         Carta2.setBackground(Color.yellow);
         carta2 = true;
         count++;
         counts.setText(String.valueOf(count));
        if(carta1 == true){
             Carta1.setVisible(false);
             Carta2.setVisible(false);
             
             count = 0;
             score++;
         carta1 = false;
         carta2 = false;
         carta3 = false;
         carta4 = false;
         carta5 = false;
         carta6 = false;
         carta7 = false;
         carta8 = false;
             Carta1.setBackground(Color.gray);
             Carta2.setBackground(Color.gray);
             
        }
         else if(count >= 2){
             
         Carta1.setBackground(Color.gray);
         Carta2.setBackground(Color.gray);
         Carta3.setBackground(Color.gray);
         Cart4.setBackground(Color.gray);
         Carta5.setBackground(Color.gray);
         Carta6.setBackground(Color.gray);
         Carta7.setBackground(Color.gray);
         Carta8.setBackground(Color.gray);
         carta1 = false;
         carta2 = false;
         carta3 = false;
         carta4 = false;
         carta5 = false;
         carta6 = false;
         carta7 = false;
         carta8 = false;
         count = 0;
         }
        SCORE.setText(String.valueOf(score));
         
        
    }//GEN-LAST:event_Carta2MouseClicked

    private void Carta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Carta2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Carta2ActionPerformed

    private void Carta3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Carta3MouseClicked
        // TODO add your handling code here:
        Carta3.setBackground(Color.green);
        carta3 = true;
        count++;
    
        counts.setText(String.valueOf(count));
        if(carta4 == true){
             Carta3.setVisible(false);
             Cart4.setVisible(false);
             score++;
            
             count = 0;
         carta1 = false;
         carta2 = false;
         carta3 = false;
         carta4 = false;
         carta5 = false;
         carta6 = false;
         carta7 = false;
         carta8 = false;
             Carta3.setBackground(Color.gray);
             Cart4.setBackground(Color.gray);
        }
         else if(count >= 2){
             
         Carta1.setBackground(Color.gray);
         Carta2.setBackground(Color.gray);
         Carta3.setBackground(Color.gray);
         Cart4.setBackground(Color.gray);
         Carta5.setBackground(Color.gray);
         Carta6.setBackground(Color.gray);
         Carta7.setBackground(Color.gray);
         Carta8.setBackground(Color.gray);
         
         count = 0;
         carta1 = false;
         carta2 = false;
         carta3 = false;
         carta4 = false;
         carta5 = false;
         carta6 = false;
         carta7 = false;
         carta8 = false;
         }
        SCORE.setText(String.valueOf(score));
    }//GEN-LAST:event_Carta3MouseClicked

    private void Cart4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cart4MouseClicked
        // TODO add your handling code here:
        Cart4.setBackground(Color.green);
        carta4 = true;
        count++;

        counts.setText(String.valueOf(count));
        if(carta3 == true){
             Carta3.setVisible(false);
             Cart4.setVisible(false);
             count = 0;
             score++;
         carta1 = false;
         carta2 = false;
         carta3 = false;
         carta4 = false;
         carta5 = false;
         carta6 = false;
         carta7 = false;
         carta8 = false;
         Carta3.setBackground(Color.gray);
         Cart4.setBackground(Color.gray);
        }
        else if(count >= 2){
            Carta1.setBackground(Color.gray);
         Carta2.setBackground(Color.gray);
         Carta3.setBackground(Color.gray);
         Cart4.setBackground(Color.gray);
         Carta5.setBackground(Color.gray);
         Carta6.setBackground(Color.gray);
         Carta7.setBackground(Color.gray);
         Carta8.setBackground(Color.gray);
         count = 0;
         carta1 = false;
         carta2 = false;
         carta3 = false;
         carta4 = false;
         carta5 = false;
         carta6 = false;
         carta7 = false;
         carta8 = false;
         }
        SCORE.setText(String.valueOf(score));
    }//GEN-LAST:event_Cart4MouseClicked

    private void Carta5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Carta5MouseClicked
        // TODO add your handling code here:
        Carta5.setBackground(Color.blue);
        carta5 = true;
        count++;

        counts.setText(String.valueOf(count));
        if(carta6 == true){
             Carta5.setVisible(false);
             Carta6.setVisible(false);
             count = 0;
             score++;
         carta1 = false;
         carta2 = false;
         carta3 = false;
         carta4 = false;
         carta5 = false;
         carta6 = false;
         carta7 = false;
         carta8 = false;
             Carta5.setBackground(Color.gray);
             Carta6.setBackground(Color.gray);
        }
         else if(count >= 2){
         Carta1.setBackground(Color.gray);
         Carta2.setBackground(Color.gray);
         Carta3.setBackground(Color.gray);
         Cart4.setBackground(Color.gray);
         Carta5.setBackground(Color.gray);
         Carta6.setBackground(Color.gray);
         Carta7.setBackground(Color.gray);
         Carta8.setBackground(Color.gray);

         count = 0;
         carta1 = false;
         carta2 = false;
         carta3 = false;
         carta4 = false;
         carta5 = false;
         carta6 = false;
         carta7 = false;
         carta8 = false;
         }
        SCORE.setText(String.valueOf(score));
    }//GEN-LAST:event_Carta5MouseClicked

    private void Carta6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Carta6MouseClicked
        // TODO add your handling code here:
        Carta6.setBackground(Color.blue);
        carta6 = true;
        count++;
        
    
        counts.setText(String.valueOf(count));
        if(carta5 == true){
             Carta5.setVisible(false);
             Carta6.setVisible(false);
             count = 0;
             score++;
         carta1 = false;
         carta2 = false;
         carta3 = false;
         carta4 = false;
         carta5 = false;
         carta6 = false;
         carta7 = false;
         carta8 = false;
             Carta5.setBackground(Color.gray);
             Carta6.setBackground(Color.gray);
        }
         else if(count >= 2){
         Carta1.setBackground(Color.gray);
         Carta2.setBackground(Color.gray);
         Carta3.setBackground(Color.gray);
         Cart4.setBackground(Color.gray);
         Carta5.setBackground(Color.gray);
         Carta6.setBackground(Color.gray);
         Carta7.setBackground(Color.gray);
         Carta8.setBackground(Color.gray);
         
   
         carta1 = false;
         carta2 = false;
         carta3 = false;
         carta4 = false;
         carta5 = false;
         carta6 = false;
         carta7 = false;
         carta8 = false;
         count = 0;
         }
        SCORE.setText(String.valueOf(score));
        
    }//GEN-LAST:event_Carta6MouseClicked

    private void Carta7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Carta7MouseClicked
        // TODO add your handling code here:
        Carta7.setBackground(Color.red);
        carta7 = true;
        count++;
        
        counts.setText(String.valueOf(count));
        if(carta8 == true){
             Carta7.setVisible(false);
             Carta8.setVisible(false);
             count = 0;
             score++;
             carta1 = false;
             carta2 = false;
             carta3 = false;
             carta4 = false;
             carta5 = false;
             carta6 = false;
             carta7 = false;
             carta8 = false;
             Carta7.setBackground(Color.gray);
             Carta8.setBackground(Color.gray);
        }
         else if(count >= 2){
         Carta1.setBackground(Color.gray);
         Carta2.setBackground(Color.gray);
         Carta3.setBackground(Color.gray);
         Cart4.setBackground(Color.gray);
         Carta5.setBackground(Color.gray);
         Carta6.setBackground(Color.gray);
         Carta7.setBackground(Color.gray);
         Carta8.setBackground(Color.gray);

         carta1 = false;
         carta2 = false;
         carta3 = false;
         carta4 = false;
         carta5 = false;
         carta6 = false;
         carta7 = false;
         carta8 = false;
         count = 0;
         }
        SCORE.setText(String.valueOf(score));
    }//GEN-LAST:event_Carta7MouseClicked

    private void Carta8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Carta8MouseClicked
        // TODO add your handling code here:
        Carta8.setBackground(Color.red);
        carta8 = true;
        count++;
        
        counts.setText(String.valueOf(count));
        if(carta7 == true){
             Carta7.setVisible(false);
             Carta8.setVisible(false);
             count = 0;
             score++;
             carta1 = false;
             carta2 = false;
             carta3 = false;
             carta4 = false;
             carta5 = false;
             carta6 = false;
             carta7 = false;
             carta8 = false;
        }
         else if(count >= 2){
         Carta1.setBackground(Color.gray);
         Carta2.setBackground(Color.gray);
         Carta3.setBackground(Color.gray);
         Cart4.setBackground(Color.gray);
         Carta5.setBackground(Color.gray);
         Carta6.setBackground(Color.gray);
         Carta7.setBackground(Color.gray);
         Carta8.setBackground(Color.gray);
         carta1 = false;
         carta2 = false;
         carta3 = false;
         carta4 = false;
         carta5 = false;
         carta6 = false;
         carta7 = false;
         carta8 = false;
         count = 0;
         }
        SCORE.setText(String.valueOf(score));
    }//GEN-LAST:event_Carta8MouseClicked

    private void ReinicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReinicioMouseClicked
        // TODO add your handling code here:
         
        
         Carta1.setBackground(Color.gray);
         Carta2.setBackground(Color.gray);
         Carta3.setBackground(Color.gray);
         Cart4.setBackground(Color.gray);
         Carta5.setBackground(Color.gray);
         Carta6.setBackground(Color.gray);
         Carta7.setBackground(Color.gray);
         Carta8.setBackground(Color.gray);
         Carta1.setVisible(true);
         Carta2.setVisible(true);
         Carta3.setVisible(true);
         Cart4.setVisible(true);
         Carta5.setVisible(true);
         Carta5.setVisible(true);
         Carta6.setVisible(true);
         Carta7.setVisible(true);
         Carta8.setVisible(true);
         carta1 = false;
         carta2 = false;
         carta3 = false;
         carta4 = false;
         carta5 = false;
         carta6 = false;
         carta7 = false;
         carta8 = false;
         score = 0;
         count = 0;
         
                
   
     switch (i){     
    case 1: 
        Carta1.setLocation(poscx_1,poscy_1);
        break;
    case 2: 
        Carta1.setLocation(poscx_2,poscy_2);
        break;
    case 3: 
        Carta1.setLocation(poscx_3,poscy_3);
        break;
    case 4: 
        Carta1.setLocation(poscx_4,poscy_4);
        break;
    case 5: 
        Carta1.setLocation(poscx_5,poscy_5);
        break;
    case 6: 
        Carta1.setLocation(poscx_6,poscy_6);
        break;
    case 7: 
        Carta1.setLocation(poscx_7,poscy_7);
        break;
    case 8: 
        Carta1.setLocation(poscx_8,poscy_8);
        break;
     
   }
     //CARTA 2
    switch (j){     
    case 1: 
        Carta2.setLocation(poscx_1,poscy_1);
        break;
    case 2: 
        Carta2.setLocation(poscx_2,poscy_2);
        break;
    case 3: 
        Carta2.setLocation(poscx_3,poscy_3);
        break;
    case 4: 
        Carta2.setLocation(poscx_4,poscy_4);
        break;
    case 5: 
        Carta2.setLocation(poscx_5,poscy_5);
        break;
    case 6: 
        Carta2.setLocation(poscx_6,poscy_6);
        break;
    case 7: 
        Carta2.setLocation(poscx_7,poscy_7);
        break;
    case 8: 
        Carta2.setLocation(poscx_8,poscy_8);
        break;
     
   } 
    //CARTA 3
   switch (k){     
    case 1: 
        Carta3.setLocation(poscx_1,poscy_1);
        break;
    case 2: 
        Carta3.setLocation(poscx_2,poscy_2);
        break;
    case 3: 
        Carta3.setLocation(poscx_3,poscy_3);
        break;
    case 4: 
        Carta3.setLocation(poscx_4,poscy_4);
        break;
    case 5: 
        Carta3.setLocation(poscx_5,poscy_5);
        break;
    case 6: 
        Carta3.setLocation(poscx_6,poscy_6);
        break;
    case 7: 
        Carta3.setLocation(poscx_7,poscy_7);
        break;
    case 8: 
        Carta3.setLocation(poscx_8,poscy_8);
        break;
     
   }
   //CARTA 4
   switch (l){     
    case 1: 
        Cart4.setLocation(poscx_1,poscy_1);
        break;
    case 2: 
        Cart4.setLocation(poscx_2,poscy_2);
        break;
    case 3: 
        Cart4.setLocation(poscx_3,poscy_3);
        break;
    case 4: 
        Cart4.setLocation(poscx_4,poscy_4);
        break;
    case 5: 
        Cart4.setLocation(poscx_5,poscy_5);
        break;
    case 6: 
        Cart4.setLocation(poscx_6,poscy_6);
        break;
    case 7: 
        Cart4.setLocation(poscx_7,poscy_7);
        break;
    case 8: 
        Cart4.setLocation(poscx_8,poscy_8);
        break;
     
   }
   //CARTA 5
   switch (m){     
    case 1: 
        Carta5.setLocation(poscx_1,poscy_1);
        break;
    case 2: 
        Carta5.setLocation(poscx_2,poscy_2);
        break;
    case 3: 
        Carta5.setLocation(poscx_3,poscy_3);
        break;
    case 4: 
        Carta5.setLocation(poscx_4,poscy_4);
        break;
    case 5: 
        Carta5.setLocation(poscx_5,poscy_5);
        break;
    case 6: 
        Carta5.setLocation(poscx_6,poscy_6);
        break;
    case 7: 
        Carta5.setLocation(poscx_7,poscy_7);
        break;
    case 8: 
        Carta5.setLocation(poscx_8,poscy_8);
        break;
     
   }
   //CARTA 6
   switch (n){     
    case 1: 
        Carta6.setLocation(poscx_1,poscy_1);
        break;
    case 2: 
        Carta6.setLocation(poscx_2,poscy_2);
        break;
    case 3: 
        Carta6.setLocation(poscx_3,poscy_3);
        break;
    case 4: 
        Carta6.setLocation(poscx_4,poscy_4);
        break;
    case 5: 
        Carta6.setLocation(poscx_5,poscy_5);
        break;
    case 6: 
        Carta6.setLocation(poscx_6,poscy_6);
        break;
    case 7: 
        Carta6.setLocation(poscx_7,poscy_7);
        break;
    case 8: 
        Carta6.setLocation(poscx_8,poscy_8);
        break;
     
   }
   //CARTA 7
   switch (o){     
    case 1: 
        Carta7.setLocation(poscx_1,poscy_1);
        break;
    case 2: 
        Carta7.setLocation(poscx_2,poscy_2);
        break;
    case 3: 
        Carta7.setLocation(poscx_3,poscy_3);
        break;
    case 4: 
        Carta7.setLocation(poscx_4,poscy_4);
        break;
    case 5: 
        Carta7.setLocation(poscx_5,poscy_5);
        break;
    case 6: 
        Carta7.setLocation(poscx_6,poscy_6);
        break;
    case 7: 
        Carta7.setLocation(poscx_7,poscy_7);
        break;
    case 8: 
        Carta7.setLocation(poscx_8,poscy_8);
        break;
     
   }
   //CARTA 8
   switch (p){     
    case 1: 
        Carta8.setLocation(poscx_1,poscy_1);
        break;
    case 2: 
        Carta8.setLocation(poscx_2,poscy_2);
        break;
    case 3: 
        Carta8.setLocation(poscx_3,poscy_3);
        break;
    case 4: 
        Carta8.setLocation(poscx_4,poscy_4);
        break;
    case 5: 
        Carta8.setLocation(poscx_5,poscy_5);
        break;
    case 6: 
        Carta8.setLocation(poscx_6,poscy_6);
        break;
    case 7: 
        Carta8.setLocation(poscx_7,poscy_7);
        break;
    case 8: 
        Carta8.setLocation(poscx_8,poscy_8);
        break;
     
   }
    
   
        
    }//GEN-LAST:event_ReinicioMouseClicked

    private void ReinicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReinicioActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ReinicioActionPerformed

    private void Apuchurrale_StarpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Apuchurrale_StarpActionPerformed
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_Apuchurrale_StarpActionPerformed

    private void Apuchurrale_StarpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Apuchurrale_StarpMouseClicked
        // TODO add your handling code here:
         Carta1.setBackground(Color.gray);
         Carta2.setBackground(Color.gray);
         Carta3.setBackground(Color.gray);
         Cart4.setBackground(Color.gray);
         Carta5.setBackground(Color.gray);
         Carta6.setBackground(Color.gray);
         Carta7.setBackground(Color.gray);
         Carta8.setBackground(Color.gray);
         Carta1.setVisible(true);
         Carta2.setVisible(true);
         Carta3.setVisible(true);
         Cart4.setVisible(true);
         Carta5.setVisible(true);
         Carta5.setVisible(true);
         Carta6.setVisible(true);
         Carta7.setVisible(true);
         Carta8.setVisible(true);
         carta1 = false;
         carta2 = false;
         carta3 = false;
         carta4 = false;
         carta5 = false;
         carta6 = false;
         carta7 = false;
         carta8 = false;
         score = 0;
         count = 0;
         
                
   
     switch (i){     
    case 1: 
        Carta1.setLocation(poscx_1,poscy_1);
        break;
    case 2: 
        Carta1.setLocation(poscx_2,poscy_2);
        break;
    case 3: 
        Carta1.setLocation(poscx_3,poscy_3);
        break;
    case 4: 
        Carta1.setLocation(poscx_4,poscy_4);
        break;
    case 5: 
        Carta1.setLocation(poscx_5,poscy_5);
        break;
    case 6: 
        Carta1.setLocation(poscx_6,poscy_6);
        break;
    case 7: 
        Carta1.setLocation(poscx_7,poscy_7);
        break;
    case 8: 
        Carta1.setLocation(poscx_8,poscy_8);
        break;
     
   }
     //CARTA 2
    switch (j){     
    case 1: 
        Carta2.setLocation(poscx_1,poscy_1);
        break;
    case 2: 
        Carta2.setLocation(poscx_2,poscy_2);
        break;
    case 3: 
        Carta2.setLocation(poscx_3,poscy_3);
        break;
    case 4: 
        Carta2.setLocation(poscx_4,poscy_4);
        break;
    case 5: 
        Carta2.setLocation(poscx_5,poscy_5);
        break;
    case 6: 
        Carta2.setLocation(poscx_6,poscy_6);
        break;
    case 7: 
        Carta2.setLocation(poscx_7,poscy_7);
        break;
    case 8: 
        Carta2.setLocation(poscx_8,poscy_8);
        break;
     
   } 
    //CARTA 3
   switch (k){     
    case 1: 
        Carta3.setLocation(poscx_1,poscy_1);
        break;
    case 2: 
        Carta3.setLocation(poscx_2,poscy_2);
        break;
    case 3: 
        Carta3.setLocation(poscx_3,poscy_3);
        break;
    case 4: 
        Carta3.setLocation(poscx_4,poscy_4);
        break;
    case 5: 
        Carta3.setLocation(poscx_5,poscy_5);
        break;
    case 6: 
        Carta3.setLocation(poscx_6,poscy_6);
        break;
    case 7: 
        Carta3.setLocation(poscx_7,poscy_7);
        break;
    case 8: 
        Carta3.setLocation(poscx_8,poscy_8);
        break;
     
   }
   //CARTA 4
   switch (l){     
    case 1: 
        Cart4.setLocation(poscx_1,poscy_1);
        break;
    case 2: 
        Cart4.setLocation(poscx_2,poscy_2);
        break;
    case 3: 
        Cart4.setLocation(poscx_3,poscy_3);
        break;
    case 4: 
        Cart4.setLocation(poscx_4,poscy_4);
        break;
    case 5: 
        Cart4.setLocation(poscx_5,poscy_5);
        break;
    case 6: 
        Cart4.setLocation(poscx_6,poscy_6);
        break;
    case 7: 
        Cart4.setLocation(poscx_7,poscy_7);
        break;
    case 8: 
        Cart4.setLocation(poscx_8,poscy_8);
        break;
     
   }
   //CARTA 5
   switch (m){     
    case 1: 
        Carta5.setLocation(poscx_1,poscy_1);
        break;
    case 2: 
        Carta5.setLocation(poscx_2,poscy_2);
        break;
    case 3: 
        Carta5.setLocation(poscx_3,poscy_3);
        break;
    case 4: 
        Carta5.setLocation(poscx_4,poscy_4);
        break;
    case 5: 
        Carta5.setLocation(poscx_5,poscy_5);
        break;
    case 6: 
        Carta5.setLocation(poscx_6,poscy_6);
        break;
    case 7: 
        Carta5.setLocation(poscx_7,poscy_7);
        break;
    case 8: 
        Carta5.setLocation(poscx_8,poscy_8);
        break;
     
   }
   //CARTA 6
   switch (n){     
    case 1: 
        Carta6.setLocation(poscx_1,poscy_1);
        break;
    case 2: 
        Carta6.setLocation(poscx_2,poscy_2);
        break;
    case 3: 
        Carta6.setLocation(poscx_3,poscy_3);
        break;
    case 4: 
        Carta6.setLocation(poscx_4,poscy_4);
        break;
    case 5: 
        Carta6.setLocation(poscx_5,poscy_5);
        break;
    case 6: 
        Carta6.setLocation(poscx_6,poscy_6);
        break;
    case 7: 
        Carta6.setLocation(poscx_7,poscy_7);
        break;
    case 8: 
        Carta6.setLocation(poscx_8,poscy_8);
        break;
     
   }
   //CARTA 7
   switch (o){     
    case 1: 
        Carta7.setLocation(poscx_1,poscy_1);
        break;
    case 2: 
        Carta7.setLocation(poscx_2,poscy_2);
        break;
    case 3: 
        Carta7.setLocation(poscx_3,poscy_3);
        break;
    case 4: 
        Carta7.setLocation(poscx_4,poscy_4);
        break;
    case 5: 
        Carta7.setLocation(poscx_5,poscy_5);
        break;
    case 6: 
        Carta7.setLocation(poscx_6,poscy_6);
        break;
    case 7: 
        Carta7.setLocation(poscx_7,poscy_7);
        break;
    case 8: 
        Carta7.setLocation(poscx_8,poscy_8);
        break;
     
   }
   //CARTA 8
   switch (p){     
    case 1: 
        Carta8.setLocation(poscx_1,poscy_1);
        break;
    case 2: 
        Carta8.setLocation(poscx_2,poscy_2);
        break;
    case 3: 
        Carta8.setLocation(poscx_3,poscy_3);
        break;
    case 4: 
        Carta8.setLocation(poscx_4,poscy_4);
        break;
    case 5: 
        Carta8.setLocation(poscx_5,poscy_5);
        break;
    case 6: 
        Carta8.setLocation(poscx_6,poscy_6);
        break;
    case 7: 
        Carta8.setLocation(poscx_7,poscy_7);
        break;
    case 8: 
        Carta8.setLocation(poscx_8,poscy_8);
        break;
     
   }    
    }//GEN-LAST:event_Apuchurrale_StarpMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ButtonExcercise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ButtonExcercise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ButtonExcercise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ButtonExcercise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ButtonExcercise_1().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Apuchurrale_Starp;
    private javax.swing.JToggleButton Cart4;
    private javax.swing.JToggleButton Carta1;
    private javax.swing.JToggleButton Carta2;
    private javax.swing.JToggleButton Carta3;
    private javax.swing.JToggleButton Carta5;
    private javax.swing.JToggleButton Carta6;
    private javax.swing.JToggleButton Carta7;
    private javax.swing.JToggleButton Carta8;
    private javax.swing.JButton Reinicio;
    private javax.swing.JLabel SCORE;
    private javax.swing.JLabel counts;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    private static class ButtonExcercise {

        public ButtonExcercise() {
        }
    }
}
