
import java.awt.Color;
import java.util.ArrayList;
import java.util.Random;
import java.util.Vector;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ikerf
 */
public class Cartas extends javax.swing.JFrame {

    /**
     * Creates new form Cartas
     */
    public Cartas() {
        initComponents();
    }
    Color_c c = new Color_c();
    String [] pruebas = new String[8];
    int cont = 0;
    int count = 0;
    String carta_1;
    String carta_2;
    String carta_3;
    String carta_4;
    String carta_5;
    String carta_6;
    String carta_7;
    String carta_8;
    boolean rojo = false;
    boolean verde = false;
    boolean amarillo = false;
    boolean azul = false;
    boolean change = false;
    Vector colores = new Vector();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Carta1 = new javax.swing.JToggleButton();
        Carta2 = new javax.swing.JToggleButton();
        Carta3 = new javax.swing.JToggleButton();
        Carta4 = new javax.swing.JToggleButton();
        Carta5 = new javax.swing.JToggleButton();
        Carta6 = new javax.swing.JToggleButton();
        Carta7 = new javax.swing.JToggleButton();
        Carta8 = new javax.swing.JToggleButton();
        check = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Carta1.setText("1");
        Carta1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Carta1MouseClicked(evt);
            }
        });

        Carta2.setText("2");
        Carta2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Carta2MouseClicked(evt);
            }
        });
        Carta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Carta2ActionPerformed(evt);
            }
        });

        Carta3.setText("3");
        Carta3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Carta3MouseClicked(evt);
            }
        });
        Carta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Carta3ActionPerformed(evt);
            }
        });

        Carta4.setText("4");
        Carta4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Carta4MouseClicked(evt);
            }
        });

        Carta5.setText("5");
        Carta5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Carta5MouseClicked(evt);
            }
        });

        Carta6.setText("6");
        Carta6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Carta6MouseClicked(evt);
            }
        });

        Carta7.setText("7");
        Carta7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Carta7MouseClicked(evt);
            }
        });

        Carta8.setText("8");
        Carta8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Carta8MouseClicked(evt);
            }
        });

        check.setText("count");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Carta2, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                            .addComponent(Carta3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Carta4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Carta5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Carta6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Carta7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Carta8, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addComponent(check))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Carta1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(check))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Carta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(Carta2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Carta3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Carta4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Carta5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Carta6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Carta7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Carta8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(128, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Carta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Carta3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Carta3ActionPerformed

    public void r_color(){
       Random r = new Random();
       ArrayList <Integer> controles = new ArrayList<>();
       controles.add(6);
       int con = 0;
        String [] colors = {"BLUE", "RED", "GREEN", "YELLOW"};
        while(controles.size()<5){
            
            
            int random = r.nextInt(4);
            c.setName(colors[random]);
            colores.add(c);
            if(random != controles.get(con)){
                controles.add(random);
                con ++;
            }
            
            
        }
        
        
    }
    public void randomizar(){
        Random r = new Random(); 
        Color_c i = (Color_c) colores.get(r.nextInt(colores.size()));
        carta_1 = i.getName();
        i = (Color_c) colores.get(r.nextInt(colores.size()));
        carta_2 = i.getName();
        i = (Color_c) colores.get(r.nextInt(colores.size()));
        carta_3 = i.getName();
        i = (Color_c) colores.get(r.nextInt(colores.size()));
        carta_4 = i.getName();
        i = (Color_c) colores.get(r.nextInt(colores.size()));
        carta_5 = i.getName();
        i = (Color_c) colores.get(r.nextInt(colores.size()));
        carta_6 = i.getName();
        i = (Color_c) colores.get(r.nextInt(colores.size()));
        carta_7 = i.getName();
        i = (Color_c) colores.get(r.nextInt(colores.size()));
        carta_8 = i.getName();
        
    }
    
   
    private void Carta1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Carta1MouseClicked
        // TODO add your handling code here:
        r_color();
        Random r = new Random(); 
        int kenobi = r.nextInt(colores.size());
        Color_c i = (Color_c) colores.get(r.nextInt(kenobi));
        colores.remove(kenobi);
        carta_1 = i.getName();
        
        cont++;
        count ++;
        switch (carta_1) {
            case "BLUE":
                Carta1.setBackground(Color.blue);
                if(azul == true){
                    Carta1.setVisible(false);
                    change = true;
                }
                else{
                    azul = true;                 
                }               
                break;
            case "RED":
                Carta1.setBackground(Color.red);
                if(rojo == true){
                    Carta1.setVisible(false);
                    change = true;
                }
                else{
                    rojo = true;
                    
                }
                break;
            case "GREEN":
                Carta1.setBackground(Color.green);
                if(verde == true){
                    Carta1.setVisible(false);
                    change = true;
                }
                else{
                    verde = true;
                }
                
                break;
            default:
                Carta1.setBackground(Color.yellow);
                if(amarillo == true){
                    Carta1.setVisible(false);
                    change = true;
                }
                else{
                    amarillo = true;
                }
                
                break;
        }
        
        if(change == true){
            Carta1.setVisible(false);
        }
        check.setText(String.valueOf(count));
        if(count >= 2){
            Carta1.setBackground(Color.gray);
            Carta2.setBackground(Color.gray);
            Carta3.setBackground(Color.gray);
            Carta4.setBackground(Color.gray);
            Carta5.setBackground(Color.gray);
            Carta6.setBackground(Color.gray);
            Carta7.setBackground(Color.gray);
            Carta8.setBackground(Color.gray);
            count = 0;
            azul = false; 
            rojo = false; 
            verde = false; 
            amarillo = false; 
            change = false; 
          
        }
        
        
    }//GEN-LAST:event_Carta1MouseClicked

    private void Carta2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Carta2MouseClicked
        // TODO add your handling code here:
        r_color();
        Random r = new Random(); 
        int kenobi = r.nextInt(colores.size());
        Color_c i = (Color_c) colores.get(r.nextInt(kenobi));
        colores.remove(kenobi);
        carta_2 = i.getName();
        
        cont++;
        count ++;
        
        switch (carta_2) {
            case "BLUE":
                Carta2.setBackground(Color.blue);
                if(azul == true){
                    Carta2.setVisible(false);
                    change = true;
                }
                else{
                    azul = true;
                }
                
                break;
            case "RED":
                Carta2.setBackground(Color.red);
                if(rojo == true){
                    Carta2.setVisible(false);
                    change = true;
                }
                else{
                    rojo = true;
                }
                break;
            case "GREEN":
                Carta2.setBackground(Color.green);
                if(verde == true){
                    Carta2.setVisible(false);
                    change = true;
                }
                else{
                    verde = true;
                }
                
                break;
            default:
                Carta2.setBackground(Color.yellow);
                if(amarillo == true){
                    Carta2.setVisible(false);
                    change = true;
                }
                else{
                    amarillo = true;
                }
                
                break;
        }
        check.setText(String.valueOf(count));
        if(change == true){
            Carta2.setVisible(false);
        }
        if(count >= 2){
            Carta1.setBackground(Color.gray);
            Carta2.setBackground(Color.gray);
            Carta3.setBackground(Color.gray);
            Carta4.setBackground(Color.gray);
            Carta5.setBackground(Color.gray);
            Carta6.setBackground(Color.gray);
            Carta7.setBackground(Color.gray);
            Carta8.setBackground(Color.gray);
            count = 0;
            azul = false; 
            rojo = false; 
            verde = false; 
            amarillo = false;
            change = false; 
          
        }
        
    }//GEN-LAST:event_Carta2MouseClicked

    private void Carta3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Carta3MouseClicked
        // TODO add your handling code here:
        r_color();
        Random r = new Random(); 
        int kenobi = r.nextInt(colores.size());
        Color_c i = (Color_c) colores.get(r.nextInt(kenobi));
        carta_3 = i.getName();
        colores.remove(kenobi);
        
        cont++;
        count ++;
        
        switch (carta_3) {
            case "BLUE":
                Carta3.setBackground(Color.blue);
                if(azul == true){
                    Carta3.setVisible(false);
                }
                else{
                    azul = true;
                }
                
                break;
            case "RED":
                Carta3.setBackground(Color.red);
                if(rojo == true){
                    Carta3.setVisible(false);
                }
                else{
                    rojo = true;
                }
                break;
            case "GREEN":
                Carta3.setBackground(Color.green);
                if(verde == true){
                    Carta3.setVisible(false);
                }
                else{
                    verde = true;
                }
                
                break;
            default:
                Carta3.setBackground(Color.yellow);
                if(amarillo == true){
                    Carta3.setVisible(false);
                    change = true;
                }
                else{
                    amarillo = true;
                }
                
                break;
        }
        check.setText(String.valueOf(count));
        if(change == true){
            Carta3.setVisible(false);
        }
        if(count >= 2){
            Carta1.setBackground(Color.gray);
            Carta2.setBackground(Color.gray);
            Carta3.setBackground(Color.gray);
            Carta4.setBackground(Color.gray);
            Carta5.setBackground(Color.gray);
            Carta6.setBackground(Color.gray);
            Carta7.setBackground(Color.gray);
            Carta8.setBackground(Color.gray);
            count = 0;
            azul = false; 
            rojo = false; 
            verde = false; 
            amarillo = false;
            change = false; 
          
        }
    }//GEN-LAST:event_Carta3MouseClicked

    private void Carta4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Carta4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Carta4MouseClicked

    private void Carta5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Carta5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Carta5MouseClicked

    private void Carta6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Carta6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Carta6MouseClicked

    private void Carta7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Carta7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Carta7MouseClicked

    private void Carta8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Carta8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Carta8MouseClicked

    private void Carta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Carta2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Carta2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cartas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cartas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cartas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cartas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cartas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Carta1;
    private javax.swing.JToggleButton Carta2;
    private javax.swing.JToggleButton Carta3;
    private javax.swing.JToggleButton Carta4;
    private javax.swing.JToggleButton Carta5;
    private javax.swing.JToggleButton Carta6;
    private javax.swing.JToggleButton Carta7;
    private javax.swing.JToggleButton Carta8;
    private javax.swing.JLabel check;
    // End of variables declaration//GEN-END:variables
}
