/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import modelo.Data;
import javax.swing.JOptionPane;
/**
 *
 * @author alanvega
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    
    Start anterior;
    
    public Menu(Start p) {
        initComponents();
        anterior = p;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newMember = new javax.swing.JButton();
        membersCheck = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        newMember.setText("Añadir Miembro");
        newMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newMemberActionPerformed(evt);
            }
        });

        membersCheck.setText("Revisar Miembros");
        membersCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                membersCheckActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(newMember))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(membersCheck)))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(newMember)
                .addGap(38, 38, 38)
                .addComponent(membersCheck)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newMemberActionPerformed
        // TODO add your handling code here:
        new NuevoMiembro(this).setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_newMemberActionPerformed

    private void membersCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_membersCheckActionPerformed
        // TODO add your handling code here:
        new Display(this).setVisible(true);
        this.setVisible(false);
        this.dispose();
        
    }//GEN-LAST:event_membersCheckActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton membersCheck;
    private javax.swing.JButton newMember;
    // End of variables declaration//GEN-END:variables
}
