/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Classes;

import java.awt.Color;

/**
 *
 * @author alanvega
 */
public class Toggle extends javax.swing.JFrame {
    boolean carta1;
    boolean carta2;
    boolean carta3;
    boolean carta4;
    boolean carta5;
    boolean carta6;
    boolean carta7;
    boolean carta8;
    int count;
    int score;
    
    

    /**
     * Creates new form Toggle
     */
    public Toggle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Carta1 = new javax.swing.JToggleButton();
        Carta2 = new javax.swing.JToggleButton();
        Carta3 = new javax.swing.JToggleButton();
        Carta4 = new javax.swing.JToggleButton();
        Carta5 = new javax.swing.JToggleButton();
        Carta6 = new javax.swing.JToggleButton();
        Carta7 = new javax.swing.JToggleButton();
        Carta8 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Carta1.setBackground(java.awt.Color.gray);
        Carta1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Carta1StateChanged(evt);
            }
        });

        Carta2.setBackground(java.awt.Color.gray);
        Carta2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Carta2StateChanged(evt);
            }
        });

        Carta3.setBackground(java.awt.Color.gray);
        Carta3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Carta3StateChanged(evt);
            }
        });

        Carta4.setBackground(java.awt.Color.gray);
        Carta4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Carta4StateChanged(evt);
            }
        });

        Carta5.setBackground(java.awt.Color.gray);
        Carta5.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Carta5StateChanged(evt);
            }
        });

        Carta6.setBackground(java.awt.Color.gray);
        Carta6.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Carta6StateChanged(evt);
            }
        });

        Carta7.setText("jToggleButton7");

        Carta8.setText("jToggleButton8");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Carta8)
                        .addGap(3, 3, 3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Carta3, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(Carta1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Carta2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Carta6, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(Carta5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Carta4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Carta7)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Carta1, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(Carta5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Carta2, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(Carta6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Carta3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Carta4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Carta7)
                    .addComponent(Carta8))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Carta1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Carta1StateChanged
        // TODO add your handling code here:
        Carta1.setBackground(Color.blue);
        count++;
         carta1 = true;
         if (carta2 = true){
         Carta1.setVisible(false);
         Carta2.setVisible(false);
         score++;
         
         jLabel1.setText("Puntaje" + score);
         }
         else{carta1 = false;} 
         if(Carta1.getColorModel() == Carta2.getColorModel()){
         Carta1.setBackground(Color.gray);
         Carta2.setBackground(Color.gray);
         Carta3.setBackground(Color.gray);
         Carta4.setBackground(Color.gray);
         Carta5.setBackground(Color.gray);
         Carta6.setBackground(Color.gray);
         Carta7.setBackground(Color.gray);
         Carta8.setBackground(Color.gray);
         
         count = 0;
         }
    }//GEN-LAST:event_Carta1StateChanged

    private void Carta2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Carta2StateChanged
        // TODO add your handling code here:
        Carta2.setBackground(Color.blue);
        count++;
         carta2 = true;
         if (carta1 == true){
         Carta1.setVisible(false);
         Carta2.setVisible(false);
         score++;
         
         jLabel1.setText("Puntaje" + score);
         }
         else{carta2 = false;} 
         if(count == 2){
         Carta1.setBackground(Color.gray);
         Carta2.setBackground(Color.gray);
         Carta3.setBackground(Color.gray);
         Carta4.setBackground(Color.gray);
         Carta5.setBackground(Color.gray);
         Carta6.setBackground(Color.gray);
         Carta7.setBackground(Color.gray);
         Carta8.setBackground(Color.gray);
         
         count = 0;
         }
    }//GEN-LAST:event_Carta2StateChanged

    private void Carta3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Carta3StateChanged
        // TODO add your handling code here:
        Carta3.setBackground(Color.red);
        count++;
         carta3 = true;
         if (carta4 = true){
         Carta3.setVisible(false);
         Carta4.setVisible(false);
         score++;
         
         jLabel1.setText("Puntaje" + score);
         }
         else if(count == 2){
         Carta1.setBackground(Color.gray);
         Carta2.setBackground(Color.gray);
         Carta3.setBackground(Color.gray);
         Carta4.setBackground(Color.gray);
         Carta5.setBackground(Color.gray);
         Carta6.setBackground(Color.gray);
         Carta7.setBackground(Color.gray);
         Carta8.setBackground(Color.gray);
         carta3 = false;
         count = 0;
         }
    }//GEN-LAST:event_Carta3StateChanged

    private void Carta4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Carta4StateChanged
        // TODO add your handling code here:
        Carta4.setBackground(Color.red);
        count++;
         carta4 = true;
         if (carta3 = true){
         Carta3.setVisible(false);
         Carta4.setVisible(false);
         score++;
         
         jLabel1.setText("Puntaje" + score);
         }
         else if(count == 2){
         Carta1.setBackground(Color.gray);
         Carta2.setBackground(Color.gray);
         Carta3.setBackground(Color.gray);
         Carta4.setBackground(Color.gray);
         Carta5.setBackground(Color.gray);
         Carta6.setBackground(Color.gray);
         Carta7.setBackground(Color.gray);
         Carta8.setBackground(Color.gray);
         carta4 = false;
         count = 0;
         }
    }//GEN-LAST:event_Carta4StateChanged

    private void Carta5StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Carta5StateChanged
        // TODO add your handling code here:
        Carta5.setBackground(Color.yellow);
        count++;
         carta5 = true;
         if (carta6 = true){
         Carta5.setVisible(false);
         Carta6.setVisible(false);
         score++;
         
         jLabel1.setText("Puntaje" + score);
         }
         else if(count == 2){
         Carta1.setBackground(Color.gray);
         Carta2.setBackground(Color.gray);
         Carta3.setBackground(Color.gray);
         Carta4.setBackground(Color.gray);
         Carta5.setBackground(Color.gray);
         Carta6.setBackground(Color.gray);
         Carta7.setBackground(Color.gray);
         Carta8.setBackground(Color.gray);
         carta5 = false;
         count = 0;
         }
    }//GEN-LAST:event_Carta5StateChanged

    private void Carta6StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Carta6StateChanged
        // TODO add your handling code here:
        Carta6.setBackground(Color.yellow);
        count++;
         carta6 = true;
         if (carta5 = true){
         Carta5.setVisible(false);
         Carta6.setVisible(false);
         score++;
         
         jLabel1.setText("Puntaje" + score);
         }
         else if(count == 2){
         Carta1.setBackground(Color.gray);
         Carta2.setBackground(Color.gray);
         Carta3.setBackground(Color.gray);
         Carta4.setBackground(Color.gray);
         Carta5.setBackground(Color.gray);
         Carta6.setBackground(Color.gray);
         Carta7.setBackground(Color.gray);
         Carta8.setBackground(Color.gray);
         carta6 = false;
         count = 0;
         }
    }//GEN-LAST:event_Carta6StateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Toggle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Toggle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Toggle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Toggle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Toggle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Carta1;
    private javax.swing.JToggleButton Carta2;
    private javax.swing.JToggleButton Carta3;
    private javax.swing.JToggleButton Carta4;
    private javax.swing.JToggleButton Carta5;
    private javax.swing.JToggleButton Carta6;
    private javax.swing.JToggleButton Carta7;
    private javax.swing.JToggleButton Carta8;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}

