
import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ikerf
 */
public class Zoom extends javax.swing.JFrame {

    /**
     * Creates new form Zoom
     */
    public Zoom() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Selection = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Progress = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Selection.setName(""); // NOI18N

        jButton1.setText("GO");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane1.setName(""); // NOI18N

        jList1.setBackground(new java.awt.Color(0, 255, 255));
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "1.Mate", "2.Info", "3.Tok", "4.B&M", "5. Fis", "6.CAS", "7. Inv", "8. Lit", "9. Fran" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel1.setFont(new java.awt.Font("Kristen ITC", 1, 48)); // NOI18N
        jLabel1.setText("By Iker Fuentes");

        Title.setBackground(new java.awt.Color(0, 255, 255));
        Title.setText("Clases del día. ");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño sin título.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");

        jLabel2.setText("Progreso del día.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(Selection, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jButton1))
                                                .addGap(18, 18, 18)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Progress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)))
                                .addGap(39, 39, 39))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Selection, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Progress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(72, 72, 72)))
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        switch(Selection.getX()){
            case 1:
                break;
            case 2:
                break;
                
        };
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int sel = (int) Selection.getValue();
        Progress.setValue(sel*10);
        switch(sel){
            case 1:
                System.out.println("\\Windows\\System32\\cmd.exe /K start " +" https://itesm.zoom.us/j/6099522495");
        {
            try {
                Runtime.getRuntime().exec("\\Windows\\System32\\cmd.exe /K start " +" https://itesm.zoom.us/j/6099522495");
            } catch (IOException ex) {
                Logger.getLogger(Zoom.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
                break;
            case 2:
                System.out.println("\\Windows\\System32\\cmd.exe /K start "+"https://itesm.zoom.us/j/9690256517");
        {
            try {
                Runtime.getRuntime().exec("\\Windows\\System32\\cmd.exe /K start "+"https://itesm.zoom.us/j/9690256517");
            } catch (IOException ex) {
                Logger.getLogger(Zoom.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
                break;  
            case 3:
                System.out.println("\\Windows\\System32\\cmd.exe /K start " +"https://itesm.zoom.us/j/9635008203");
        {
            try {
                Runtime.getRuntime().exec("\\Windows\\System32\\cmd.exe /K start "+"https://itesm.zoom.us/j/9635008203");
            } catch (IOException ex) {
                Logger.getLogger(Zoom.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
                break;  
            case 4:
                System.out.println("\\Windows\\System32\\cmd.exe /K start " +"https://itesm.zoom.us/j/4461211068");
        {
            try {
                Runtime.getRuntime().exec("\\Windows\\System32\\cmd.exe /K start "+"https://itesm.zoom.us/j/4461211068");
            } catch (IOException ex) {
                Logger.getLogger(Zoom.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
                break;
            case 5:
                System.out.println("\\Windows\\System32\\cmd.exe /K start "+"https://itesm.zoom.us/j/6349096462");
        {
            try {
                Runtime.getRuntime().exec("\\Windows\\System32\\cmd.exe /K start "+"https://itesm.zoom.us/j/6349096462");
            } catch (IOException ex) {
                Logger.getLogger(Zoom.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
                break;
            case 6:
        {
            try {
                Runtime.getRuntime().exec("\\Windows\\System32\\cmd.exe /K start "+"https://itesm.zoom.us/j/9806315931");
            } catch (IOException ex) {
                Logger.getLogger(Zoom.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
                System.out.println("\\Windows\\System32\\cmd.exe /K start "+"https://itesm.zoom.us/j/9806315931");
                break;
            case 7:
        {
            try {
                Runtime.getRuntime().exec("\\Windows\\System32\\cmd.exe /K start "+"https://itesm.zoom.us/j/3818259874");
            } catch (IOException ex) {
                Logger.getLogger(Zoom.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
                System.out.println("\\Windows\\System32\\cmd.exe /K start " +"https://itesm.zoom.us/j/3818259874");
                break;
            case 8:
                System.out.println("\\Windows\\System32\\cmd.exe /K start "+"https://itesm.zoom.us/j/7884631163");
        {
            try {
                Runtime.getRuntime().exec("\\Windows\\System32\\cmd.exe /K start "+"https://itesm.zoom.us/j/7884631163");
            } catch (IOException ex) {
                Logger.getLogger(Zoom.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
                break;
            case 9:
        {
            try {
                Runtime.getRuntime().exec("\\Windows\\System32\\cmd.exe /K start "+"https://itesm.zoom.us/j/5346104356");
            } catch (IOException ex) {
                Logger.getLogger(Zoom.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
                System.out.println("\\Windows\\System32\\cmd.exe /K start "+"https://itesm.zoom.us/j/5346104356");
                break; 
            default:
        {
            try {
                Runtime.getRuntime().exec("\\Windows\\System32\\cmd.exe /K start "+"https://youtu.be/dQw4w9WgXcQ");
            } catch (IOException ex) {
                Logger.getLogger(Zoom.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
                Title.setText("Inválido");
                Title.setForeground(Color.red);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Zoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Zoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Zoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Zoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Zoom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar Progress;
    private javax.swing.JSpinner Selection;
    private javax.swing.JLabel Title;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
